services:
  - type: web
    name: fortune-line-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: LINE_USER_ID
        sync: false
      - key: AI_IMAGE_URL
        value: https://i.imgur.com/u5n4AAu.png

  - type: cron
    name: morning-fortune
    schedule: "0 23 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: curl -X POST https://fortune-line-bot.onrender.com/send_fortune
